### ISSUE TITLE
Add async evaluation

### ISSUE THREAD

**Issue by jamescasbon** [gregsexton/ob-ipython#18]
This looks very good but, to really be useful, it needs to be asynchronous with the kernel evaluation.

Using 'import time; time.sleep(10)' blocks for 10s.

**Comment by gregsexton** [comment]
Async would be great. Completely agree. I took a look in to this when developing ob-ipython but babel itself doesn't support it. I seem to recall I found a mailing list discussion but not a lot of action.

In short: this is blocked on org babel supporting async evaluation.

**Comment by jamescasbon** [comment]
Ok, thanks for letting me know. I don't think babel is going to be much use to me until that is sorted out.

**Comment by girip** [comment]
Hi,

I have been trying to see if I could run python blocks asynchronous within ob-ipython. I think it may be possible to use the url-retrieve function instead of url-retrieve-synchronously. The following code for ob-ipython--execute-request function works and currently dumps the results to a tmp file which is identical to output with  url-retrieve-synchronously while being asynchronous.

(let ((url-request-data "import time; time.sleep(10); print 'foo'")
      (name "foo-session")
      (url-request-method "POST"))
  (with-current-buffer (url-retrieve
                        (format "http://%s:%d/execute/%s"
                                ob-ipython-driver-hostname
                                ob-ipython-driver-port
                                name)  
                        (lambda (outp) (write-region outp nil "~/tmp"))
                        )
    ))

but I am not able to send the result to existing parser to extract the output from the file. I am a novice to elisp, could someone help with it correctly passing to the existing parser?

I tried the following but it was unsuccessful:
(let ((url-request-data "import time; time.sleep(1); print 'tubelight'")
      (name "transition")
      (url-request-method "POST"))
  (with-current-buffer (insert-buffer "tmp")
    (if (>= (url-http-parse-response) 400)
        (ob-ipython--dump-error (buffer-string))
      (goto-char url-http-end-of-headers)
      (let ((json-array-type 'list))
        (json-read)))    
    ) 
  )

Once we pass it to parser correctly, I think we can use some of the code from John Kitchin (http://kitchingroup.cheme.cmu.edu/blog/2015/11/20/Asynchronously-running-python-blocks-in-org-mode/) to update the output to the correct location in org-file and should be able to run the blocks asynchronously.

**Comment by girip** [comment]
I think I added the async support for running executing the ipython blocks. 
Basically it uses url-retrieve and dumps the output to a temporary file which is then read back as output to the org-file. This is my first elisp coding, so the code may not be perfect and please feel free to modify them.
It needs the tag :async t in org block like for executing asynchronously and the output image file needs be given as :async-file file.png. I am not able to use the :file tag for the output image file. Maybe someone else could fix this. 

I submitted the pull request and also the forked version is in 
https://github.com/girip/ob-ipython/blob/pull-request-async

**Comment by gregsexton** [comment]
#40

**Comment by gregsexton** [comment]
Done!

**Comment by erdogdu** [comment]
This is really great, thanks!
I was wondering if ob-ipython-stdout can be read real time in emacs while a source block is running.
