### ISSUE TITLE
publish to melpa

### ISSUE THREAD

**Issue by zweifisch** [gregsexton/ob-ipython#2]
:pray:

**Comment by gregsexton** [comment]
I'm on it.

**Comment by mattdeboard** [comment]
This is a personal crusade of mine, but would you please consider *also* publishing to MELPA stable? It is very easy and no additional effort beyond tagging releases. MELPA looks for tags, and publishes the latest one.

**Comment by gregsexton** [comment]
@mattdeboard, marking releases makes sense for libraries designed for code consumption. For a project like this, where the HEAD of mainline acts as a 'release branch' with the 'best' version yet, tagging is somewhat arbitrary and just something to forget. Having said this, if a simple tag is all that is necessary I don't have a problem with it. Just wouldn't be surprised if the stable version drifts from the repo and is forgotten to be updated. What are your thoughts?

**Comment by gregsexton** [comment]
https://github.com/milkypostman/melpa/pull/2845

**Comment by mattdeboard** [comment]
I agree with you, it does seem redundant for projects like these, no doubt about it. I maintain [elixir-mode](https://github.com/elixir-lang/emacs-elixir), which I think could easily do with an "unstable"-only release since it's not a library. But I made the choice to do versioning and am glad I did.

That is because there are plenty of users out there would would prefer to use only stable releases for everything, even non-library ones (a popular package that does stable releases that differ greatly from `HEAD` that comes to mind is `web-mode`). If they point their config at `stable.melpa.org`, they won't get updates to packages that don't do "stable" releases, e.g. `ob-ipython`. They can point at both `stable.melpa.org` AND `melpa.org` of course, but then they're picking through duplicate package names and praying they get the stable version. 

So yeah for this package it is overkill to do a "stable" release. And the effort really is to support a small minority of users (for `elixir-mode` only like 3.4% of users get the stable release). But I personally think it's worth it, especially for the quite minimal effort needed to get it going. I won't sit here and preach about it anymore, and you've done a really amazing job on this package regardless. I just ask you to please consider it. [This script](https://gist.github.com/mattdeboard/68f7009e847e36e6c107) will handle all the heavy lifting associated with tagging & maintaining a changelog, *if* you decide to do that. [Here](http://mattdeboard.net/2014/01/14/automatic-changelog-generation-with-git/) is a blog post that explains how/why.

Thanks for at least being willing to hear me out.

**Comment by gregsexton** [comment]
> That is because there are plenty of users out there would would prefer to use only stable releases for everything, even non-library ones (a popular package that does stable releases that differ greatly from HEAD that comes to mind is web-mode). If they point their config at stable.melpa.org, they won't get updates to packages that don't do "stable" releases, e.g. ob-ipython.

Great point. I hadn't considered this. Will push a tag soon.

**Comment by mattdeboard** [comment]
:+1:

**Comment by gregsexton** [comment]
My melpa pull request has been merged. Several people are still complaining about some show-stopper issues: I'll push a tag once these have been addressed.
