### ISSUE TITLE
ipython v4.2.0 and ob-ipython seem not to play well

### ISSUE THREAD

**Issue by osdf** [gregsexton/ob-ipython#63]
Hi,
it seems that command line parameters have changed. I get (cropped to the main information)
```
[TerminalIPythonApp] CRITICAL | Bad config encountered during initialization:
[TerminalIPythonApp] CRITICAL | Unrecognized flag: '--port'

Process client-driver exited abnormally with code 1
```
and
```
[TerminalIPythonApp] CRITICAL | Bad config encountered during initialization:
[TerminalIPythonApp] CRITICAL | Unrecognized flag: '--conn-file'

Process kernel-default exited abnormally with code 1
```
(which probably also results in Issue #59). It seems that some of the cli parameters have changed, as indicated here: https://github.com/ipython/ipython/wiki/Cookbook:-Connecting-to-a-remote-kernel-via-ssh

```
% jupyter --version
4.1.0
```

```
% ipython --version
4.2.0
```

**Comment by singletS** [comment]
(should this be a separate issue?)

ipython 4.2.0 seems to cause problems with ``ob-ipython-inspect``:

``ob-ipython--dump-error: There was a fatal error trying to process the request. See *ob-ipython-debug*``

Output from debug buffer:
```
HTTP/1.1 500 Internal Server Error
Content-Type: text/html; charset=UTF-8
Server: TornadoServer/4.3
Content-Length: 93
Date: Mon, 16 May 2016 13:30:21 GMT

<html><title>500: Internal Server Error</title><body>500: Internal Server Error</body></html>
```

```
ipython --version
4.2.0
jupyter --version 
4.1.0
emacs --version
GNU Emacs 25.1.50.2
```
Thanks

**Comment by EmperorDali** [comment]
I'm having the same error referenced in the first post (Unrecognized flag: '--port') on ipython 4.1.1

This renders ob-ipython completely unusable, since the interpreter can't start.

```
CIVIC-TV:~ dynerman$ ipython --version
4.1.1
CIVIC-TV:~ dynerman$ jupyter --version
4.1.0
```

**Comment by xin-jin** [comment]
any news on this? running into exactly the same issues.

**Comment by xin-jin** [comment]
@osdf I just modified the code according to that thread, but didn't solve the problem. Same error info.

**Comment by osdf** [comment]
What a pity. Thanks for trying!

**Comment by EmperorDali** [comment]
I've managed to fix this, at least on my machine.

The problem seems to be that I had python-shell-interpreter set to ipython, so ob-ipython.el was trying to launch its driver.py using ipython. In this situation, the driver.py command line args are intercepted by ipython, which complains about not recognizing them and errors out. 

I submitted a pull request for a patch that fixes this by adding "--" to the command line, which should work both with python and ipython. 

In the meantime you can fix it locally by switching python-shell-interpreter to python, or, if you're really inclined, you can check out the (temporary) branch with the bug fix (or even just copy/paste the diff into your ob-ipython.el, it's only 2 lines):

https://github.com/EmperorDali/ob-ipython/tree/fix-ipython-driver-args

**Comment by osdf** [comment]
@EmperorDali Thank you, this seems to work (mostly), see below. ```C-c C-c``` and ```C-c C-v C-z``` are doing as advertised. In the REPL buffer, I get the following error/warning at the top:

```
[TerminalIPythonApp] WARNING | Subcommand `ipython console` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter console` in the future
[ZMQTerminalIPythonApp] CRITICAL | Could not find existing kernel connection file emacs-default.json

Process Python exited abnormally with code 1
[TerminalIPythonApp] WARNING | Subcommand `ipython console` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter console` in the future
Jupyter Console 4.1.1
```
Any ideas/comments? I would leave the issue open, until your fix is merged, is that ok?
